blank_issues_enabled: true
contact_links:
  - name: Questions and Help (on CreditChain Developer Discussions)
    url: https://github.com/ibankio/creditchain/issues
    about: Support and other questions are handled by the team and community via GitHub Issues.
  - name: Security Reporting
    url: https://github.com/ibankio/creditchain/security
    about: Report security issues via the repository security workflow.
