name: "Get latest CreditChain CLI"
description: |
  Fetches the latest released CreditChain CLI.
inputs:
  destination_directory:
    description: "Directory to install the CLI in"
    required: true
  repository_url:
    description: "Optional git repository URL to install the CLI from"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install CLI from CreditChain repository
      shell: bash
      run: |
        REPO_URL="${{ inputs.repository_url }}"
        if [[ -z "${REPO_URL}" ]]; then
          REPO_URL="${{ github.server_url }}/${{ github.repository }}.git"
        fi
        mkdir -p "${{ inputs.destination_directory }}"
        RUSTFLAGS="--cfg tokio_unstable" cargo install --locked --git "${REPO_URL}" --profile cli creditchain
        cp "$HOME/.cargo/bin/creditchain" "${{ inputs.destination_directory }}/creditchain"
        chmod +x "${{ inputs.destination_directory }}/creditchain"
